apiVersion: batch/v1
kind: Job
metadata:
  name: database-migration
  namespace: ecommerce
  labels:
    app: database-migration
    type: maintenance
spec:
  template:
    metadata:
      labels:
        app: database-migration
        type: maintenance
    spec:
      restartPolicy: OnFailure
      containers:
      - name: migration
        image: ecommerce/db-migration:v1.0.0
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: database
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: data-backup
  namespace: ecommerce
  labels:
    app: data-backup
    type: maintenance
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: data-backup
            type: maintenance
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: ecommerce/backup-tool:v1.0.0
            env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: password
            - name: BACKUP_LOCATION
              value: "s3://ecommerce-backups/"
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "200m"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-cleanup
  namespace: ecommerce
  labels:
    app: cache-cleanup
    type: maintenance
spec:
  schedule: "0 4 * * 0"  # Weekly on Sunday at 4 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cache-cleanup
            type: maintenance
        spec:
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: redis:7-alpine
            command:
            - /bin/sh
            - -c
            - |
              redis-cli -h redis-service -p 6379 -a $REDIS_PASSWORD FLUSHDB
            env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-auth
                  key: password
            resources:
              requests:
                memory: "64Mi"
                cpu: "50m"
              limits:
                memory: "128Mi"
                cpu: "100m"