apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ecommerce-microservices

resources:
- namespace.yaml
- secrets.yaml
- configmaps.yaml
- storage.yaml
- databases.yaml
- deployments.yaml
- services.yaml
- ingress.yaml
- rbac.yaml
- jobs.yaml
- monitoring.yaml

commonLabels:
  platform: ecommerce
  managed-by: kustomize

images:
- name: ecommerce/user-service
  newTag: v1.2.0
- name: ecommerce/product-service  
  newTag: v1.1.0
- name: ecommerce/order-service
  newTag: v1.0.5
- name: ecommerce/payment-service
  newTag: v1.0.3
- name: ecommerce/api-gateway
  newTag: v2.1.0

replicas:
- name: user-service
  count: 3
- name: product-service
  count: 3
- name: order-service
  count: 2
- name: payment-service
  count: 2
- name: api-gateway
  count: 2