apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: ecommerce
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: c2VjcmV0UGFzcw==  # secretPass
  database: ZWNvbW1lcmNl  # ecommerce
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: ecommerce
type: Opaque
data:
  password: cmVkaXNQYXNz  # redisPass
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: ecommerce
type: Opaque
data:
  secret-key: andTZWNyZXRLZXk=  # jwtSecretKey