apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- configmap.yaml

namePrefix: base-

commonLabels:
  environment: base
  managed-by: kustomize