apiVersion: v1
kind: Secret
metadata:
  name: vault-tls-secret
  namespace: default
type: Opaque
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVRXBjZUhjVHlqcFpGOXZhcUVaVHJJQ2UyOGdRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRU9NQXdHQTFVRUF3d0ZkbUYxYkhRd1F6UXdWbUYxYkhSRE1qZ3dGbUYxYkhRd1F6UXd...
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-ca-cert
  namespace: default
type: Opaque
data:
  ca.pem: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lVRXBjZUhjVHlqcFpGOXZhcUVaVHJJQ2UyOGdRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lqRU9NQXdHQTFVRUF3d0ZkbUYxYkhRd1F6UXdWbUYxYkhRd1F6...
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: default
type: Opaque
data:
  token: czAuSGJMaklBY1lEWkRGWG0wU3JHUnVNdHNnOGkxdDNtRHN6akZkNTBjSTNVYTJTUlc=