apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
- name: api-server
  count: 5

patches:
- path: deployment-patch.yaml

configMapGenerator:
- name: prod-config
  literals:
  - database.url=prod-db:5432
  - log.level=warn